[manifest]
version = "1.0.0"
dump_lua = true
priority = 0

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if SMODS.optional_features.object_weights then"
position = "before"
match_indent = true
payload = '''
if OTFS.is_plant_showdown() then
  local boss = 'bl_plant'
  G.GAME.bosses_used[boss] = (G.GAME.bosses_used[boss] or 0) + 1
  return boss
end
'''